name: Semgrep Scan  # Nome do workflow

on:
  push:
    branches:
      - master  # Executa o pipeline quando houver push para o branch "main"
  pull_request:
    branches:
      - master  # Executa o pipeline quando houver um pull request para o branch "main"

jobs:
  semgrep:
    runs-on: ubuntu-latest  # Define o sistema operacional que será usado (Ubuntu)

    steps:
      # Passo 1: Faz o checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Executa o Semgrep
      - name: Set up Python
        uses: actions/checkout@v4  # Usa a ação oficial do Semgrep
        with:
          python-version: '3.x'

      - name: Install semgrep
        run: pip install semgrep 

      - name: Run semgrep
        run: semgrep --config auto --eror || true 